apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflows-ui
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argo-workflows
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/argoproj/argo-workflows
    targetRevision: HEAD
    path: manifests/ui
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
