apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    chart: argo
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 3.5.11
    helm:
      releaseName: argo-workflows
      insecure: true # This is where you specify insecure TLS verification
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
