apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd      
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/chesney/self-managed-argo
    targetRevision: HEAD
    path: applications
  syncPolicy:
    syncOptions:
      - CreateNamespace=true