apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- argo-rollouts.yaml

patches:
- target:
    kind: Deployment
    name: argocd-server
    version: apps/v1
  path: patch.yaml