apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.16.1    # Specify the chart version you want to use
    chart: sealed-secrets
    helm:
      releaseName: sealed-secrets-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system    # Sealed Secrets is typically installed in kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true